const transactionTypes = {
    GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
    GET_TRANSACTIONS_ERROR: "GET_TRANSACTIONS_ERROR",
    CLEANUP_TRANSACTIONS: "CLEANUP_TRANSACTIONS"
}

export default transactionTypes