const profileActionTypes = {
    GET_PROFILE: 'GET_PROFILE',
    PROFILE_ERROR: 'PROFILE_ERROR',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    CLEAR_SINGLE_PROFILE: 'CLEAR_SINGLE_PROFILE',
    CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_VIEW: 'UPDATE_PROFILE_VIEW',
    CLEANUP_PROFILES: 'CLEANUP_PROFILES'
}

export default profileActionTypes