const profileActionTypes = {
    GET_PROFILE: 'GET_PROFILE',
    PROFILE_ERROR: 'PROFILE_ERROR',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    CLEAR_SINGLE_PROFILE: 'CLEAR_SINGLE_PROFILE'
}

export default profileActionTypes