const authActionTypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOG_OUT: 'LOG_OUT',
    LOGIN_LOADING: 'LOGIN_LOADING',
    REGISTER_LOADING: 'REGISTER_LOADING'
}

export default authActionTypes